"""Add TCG cards table

Revision ID: add_tcg_cards_table
Revises: 4d7be6564407
Create Date: 2025-08-03 14:50:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "add_tcg_cards_table"
down_revision = "4d7be6564407"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tcg_cards",
        sa.Column("id", sa.VARCHAR(length=50), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("supertype", sa.VARCHAR(length=50), nullable=True),
        sa.Column("subtypes", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("level", sa.VARCHAR(length=10), nullable=True),
        sa.Column("hp", sa.VARCHAR(length=10), nullable=True),
        sa.Column("types", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("evolves_from", sa.VARCHAR(length=100), nullable=True),
        sa.Column("evolves_to", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("abilities", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("attacks", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("weaknesses", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("resistances", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "retreat_cost", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("converted_retreat_cost", sa.INTEGER(), nullable=True),
        sa.Column("set_id", sa.VARCHAR(length=50), nullable=True),
        sa.Column("set_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("set_series", sa.VARCHAR(length=100), nullable=True),
        sa.Column("number", sa.VARCHAR(length=20), nullable=True),
        sa.Column("artist", sa.VARCHAR(length=100), nullable=True),
        sa.Column("rarity", sa.VARCHAR(length=50), nullable=True),
        sa.Column("flavor_text", sa.TEXT(), nullable=True),
        sa.Column(
            "national_pokedex_numbers",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("image_small", sa.VARCHAR(length=255), nullable=True),
        sa.Column("image_large", sa.VARCHAR(length=255), nullable=True),
        sa.Column("legalities", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="tcg_cards_pkey"),
    )
    with op.batch_alter_table("tcg_cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_tcg_cards_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("idx_tcg_cards_set"), ["set_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tcg_cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_tcg_cards_set"))
        batch_op.drop_index(batch_op.f("idx_tcg_cards_name"))

    op.drop_table("tcg_cards")
    # ### end Alembic commands ###
